#!/bin/bash
#
# Filter the arguments from a bash script
# Copyright 2014 Tiago Hillebrandt <tiago@tiagohillebrandt.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

args=(`echo $1 | egrep -o "\-\-(.*)( |=(.*)|$)"`)

for arg in ${args[@]}; do
    echo $arg | egrep -q "^--" || continue

    arg=`echo $arg | sed "s/^--//g"`

    if echo $arg | grep -q "="; then
        name=`echo $arg | cut -d= -f1`
        value=`echo $arg | cut -d= -f2`
    else
        name=$arg
        value="1"
    fi

    name=`echo "arg_$name" | sed "s/[^0-9a-Z_]//g"`

    eval "$name=\$value"
done
